
project_id = "ehqdibhqhevjnknojogm"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
# JWT expiry in seconds (4 hours for better UX, refresh tokens handle security)
jwt_expiry = 14400
# Note: refresh_token_rotation_enabled not supported in this Supabase CLI version
# Configure these settings in the Supabase Dashboard under Authentication > Settings

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
# Note: min_password_length not supported in config.toml for this version
# Configure password requirements in Supabase Dashboard under Authentication > Policies

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true

[analytics]
enabled = false

[functions.generate-notebook-content]
verify_jwt = true

[functions.send-chat-message]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.process-document-callback]
verify_jwt = false

[functions.process-additional-sources]
verify_jwt = true

[functions.scheduled-podcast-processing]
verify_jwt = false
